### ISSUE TITLE
Input your own data error

### ISSUE THREAD

**Issue by LeahHunt** [EducationShinyAppTeam/Testing_and_CI_Relationship#1]
If you enter the "App" section using one of the two default data sets then try to return to data entry and try to enter your own data, the app crashes.

**Comment by neilhatfield** [comment]
This was replicated under the following conditions:
1. Launched the app.
2. Clicked the Explore button and went to the Testing and CI Relationship tab.
3. Clicked on the Choose a Data Set Tab.
4. Selected InputYourOwn

Resulting Messages from the console:
```
Warning: Error in sample.int: invalid first argument
  74: sample.int
  73: sample
  72: observeEventHandler [/Users/neilhatfield/Documents/GitHub/Boast/Reviews/Testing_and_CI_Relationship/server.R#97]
   1: runApp
```
